version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network

  web:
    image: nginx:latest
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80" # Map host port 8000 to container port 80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
